version: '3.8'

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: lms-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    ports:
      - "8000:8000"
    networks:
      - lms-network
    depends_on:
      - redis
    environment:
      - APP_ENV=local
      - VITE_APP_URL=http://localhost:5173
      - REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "php", "artisan", "config:clear"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Vite Development Server
  vite:
    image: node:18-alpine
    container_name: lms-vite
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    networks:
      - lms-network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Service
  redis:
    image: redis:alpine
    container_name: lms-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - lms-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  lms-network:
    driver: bridge